# Generated by Django 5.1.4 on 2025-02-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia_da_semana', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.TextField(blank=True, null=True)),
                ('instrutor_id', models.IntegerField(blank=True, null=True)),
                ('sala_id', models.IntegerField(blank=True, null=True)),
                ('tipo_aula_id', models.IntegerField(blank=True, null=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.dia')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.horario')),
            ],
        ),
    ]
