# Generated by Django 5.1.4 on 2025-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='dia',
            field=models.DateField(default=None),
        ),
    ]
